### ISSUE TITLE
PipeflowNotConverged when sink doesn't require mass flow

### ISSUE THREAD

**Issue by JXTriphase** [e2nIEE/pandapipes#570] opened 2023-10-31 06:51 UTC
I set the mdot_kg_per_s=0 for sink1 in /tutorials/temperature_calculation.ipynb and the pandapipes.pipeflow raised PipeflowNotConverged. I also noticed that scipy.sparse.linalg raised a warning, MatrixRankWarning: Matrix is exactly singular. PipeflowNotConverged error also occurs after setting in_service=False for sink1. Does that mean a sink must require a positive mass flow from the net? What can I do if I want to build a sink that sometimes doesn't require mass flow?

**Comment by dlohmeier** [comment] 2023-10-31 07:21
Hello @JXTriphase ,
thanks for raising this issue. The problem is that setting the sink's mass flow to 0 leads to 0 flow in some of the branches (pipe 3), which then used to be problematic when creating the Jacobian matrix (full 0 lines). It can be solved by separating the connectivity check for hydraulics and heat transfer calculation, which has only recently been fixed on the develop branch. We will try to get a release out as soon as possible, but need to fix another installation problem before and we only have limited man power atm. To solve this problem at short notice for you, I would suggest one of the following options:
- checkout the develop branch of pandapipes via git (cf. https://www.pandapipes.org/start/)
- install a specific tag with pip, which I also had to use recently for my own production code: pip install pandapipes @ https://github.com/dlohmeier/pandapipes/archive/connectivity_separate_0.8.5.tar.gz
Does that help for the time being?
Kind regards

**Comment by JXTriphase** [comment] 2023-10-31 08:20
Hi @dlohmeier ,
thank you very much for your quick response. That problem is solved now. I will keep following this project and learning from it. Thanks again for your help.

**Comment by dlohmeier** [comment] 2024-01-12 14:50
With the new release of pandapipes 0.9.0 this problem should be addressed now. I will close the issue, but feel free to ask further questions or reopen if the problem occurs again.

**Closed by dlohmeier** 2024-01-12 14:50 UTC
