### ISSUE TITLE
Modelling vector coupling components using P2GControlMultiEnergy to interact with power, gas and hydrogen networks

### ISSUE THREAD

**Issue by akhiljoseph007** [e2nIEE/pandapipes#399] opened 2022-08-17 13:15 UTC
I am trying to model the interaction of a P2G between electricity and gas network and fuel cell between hydrogen and electricity network which operates simultaneously.  That means, there are three networks in the multinet.

I use function P2GControlMultiEnergy() and G2PControlMultiEnergy(). When I run the code I get the error as follows.

**_ValueError: NumPy boolean array indexing assignment cannot assign 2 input values to the 1 output values where the mask is true_**

I can run either P2G of FC at a given time without any errors. But not together. Any solution to fix this problem? Thanks in advance. 

![image](https://user-images.githubusercontent.com/67893281/185143581-fe6788ad-be11-40b4-b404-af4f05f13679.png)

**Comment by jkisse** [comment] 2022-08-17 13:22
Hi akhiljoseph007, 
thanks for using pandapipes and raising this issue. Could you please provide a minimal example so that we can reproduce the problem and look into it?

**Comment by akhiljoseph007** [comment] 2022-08-17 13:34
import pandapipes as ppipes
import pandapower as ppower

from pandapipes import networks as g_nw
from pandapower import networks as e_nw
from pandapipes.multinet.create_multinet import create_empty_multinet, add_net_to_multinet
from pandapipes.multinet.control.controller.multinet_control import P2GControlMultiEnergy, G2PControlMultiEnergy
from pandapipes.multinet.control.run_control_multinet import run_control
from pandapipes.multinet.control.controller.multinet_control import coupled_p2g_const_control, \
    coupled_g2p_const_control
    
from pandas import DataFrame
from numpy.random import random
from pandapower.timeseries import DFData

import numpy as np
import matplotlib.pyplot as plt

def create_data_source(n_timesteps=10):
    profiles = DataFrame()
    profiles['e_load'] = random(n_timesteps) * 8
    profiles['g_load'] = random(n_timesteps) * 0.1
    ds = DFData(profiles)

    return profiles, ds

profiles, ds = create_data_source(10)    
time_steps = range(10)  

LoG         = np.ones(10)
LoG[0]      = 0.5
Storage_Cap = 0.07  

def create_mutlinet():
    net_power = e_nw.example_simple()
    net_gas = g_nw.gas_meshed_square()
    net_gas.junction.pn_bar = net_gas.ext_grid.p_bar = 30
    net_gas.pipe.diameter_m = 0.4
    net_gas.controller.rename(columns={'controller': 'object'}, inplace=True) # due to new version
    ppipes.create_fluid_from_lib(net_gas, 'hydrogen', overwrite=True)
    
    net_hyd = ppipes.create_empty_network(fluid="hydrogen")
    net_hyd.junction.pn_bar = net_hyd.ext_grid.p_bar = 30
    net_hyd.controller.rename(columns={'controller': 'object'}, inplace=True) # due to new version
    
    
    VCS1_in = ppipes.create_junction(net_hyd, pn_bar=1, tfluid_k=288.15, name="VCS1_in")
    VCS1_out = ppipes.create_junction(net_hyd, pn_bar=1, tfluid_k=288.15, name="VCS1_out")
    
    
    multinet = create_empty_multinet('tutorial_multinet')
    add_net_to_multinet(multinet, net_power, 'net_power')
    add_net_to_multinet(multinet, net_gas, 'net_gas')
    add_net_to_multinet(multinet, net_hyd, 'net_hyd')
    
    return net_power, net_gas, net_hyd, multinet
    

def electrolyser(net_power, net_gas, net_hyd, multinet):
    electzr_in   = ppower.create_load(net_power, bus = 0, p_mw=0.5, name='Electrolyser consumption' )
    electzr_out  = ppipes.create_source(net_hyd, junction=0, mdot_kg_per_s=0.0, name='Electrolyser out')
    electzr_ctrl = P2GControlMultiEnergy(multinet, electzr_in, electzr_out, efficiency = 0.6, 
                                          name_power_net= 'net_power', name_gas_net='net_hyd')
    ppipes.create_ext_grid(net_hyd, junction=0, p_bar=30, t_k=288.15)
    
    return electzr_in,electzr_out,electzr_ctrl
    
def fuel_cell(net_power, net_gas, net_hyd, multinet):
    fuel_cell_in  = ppipes.create_sink(net_hyd, junction = 1, mdot_kg_per_s=0.01, name='Fuel cell feed in')
    fuel_cell_out = ppower.create_sgen(net_power, bus=0, p_mw=0, name='fuel-cell output')
    fuel_cell_ctrl = G2PControlMultiEnergy(multinet, fuel_cell_out, fuel_cell_in, efficiency=0.65,
                                            name_power_net= 'net_power', name_gas_net='net_hyd')


    ppipes.create_ext_grid(net_hyd, junction=1, p_bar=30, t_k=288.15)
    ppipes.create_source(net_hyd, junction=1, mdot_kg_per_s=0.0000001)
    
    return fuel_cell_in, fuel_cell_out, fuel_cell_ctrl
        

def coupling_p2g(net_power, net_gas, multinet):
    
    # create elements corresponding to conversion units
    # Power-to-gas 1
    global p2g_1_el,p2g_1_gas
    p2g_1_el = ppower.create_load(net_power, bus=0, p_mw=1, name="p2g1 consumption")
    p2g_1_gas = ppipes.create_source(net_gas, junction=0, mdot_kg_per_s=0, name="p2g1 feed in")
    p2g_1_ctrl = P2GControlMultiEnergy(multinet, p2g_1_el, p2g_1_gas, efficiency=0.8,
                                 name_power_net="net_power", name_gas_net="net_gas")
    
    


def plot(LoG):
    print('-----------------LoG-----------------------')
    print(LoG)
    x = time_steps
    y = LoG*100
    
    plt.xlabel("time step")
    plt.ylabel("LoG [%]")
    plt.ylim(0,100)
    plt.title("Level-of-Gas")
    plt.plot(x, y, "r-o")
    #plt.grid()
    plt.show()
    

def main():
    for i in time_steps:    
        
        net_power, net_gas, net_hyd, multinet = create_mutlinet()
        coupling_p2g(net_power, net_gas, multinet)
        
        
        net_power.load['p_mw'][0] = profiles['e_load'][i]    
        
        
        if net_power.gen['p_mw'][0] > net_power.load['p_mw'][0]:
            electzr_in,electzr_out,electzr_ctrl = electrolyser(net_power, net_gas, net_hyd, multinet)
    
            
        if net_power.gen['p_mw'][0] < net_power.load['p_mw'][0]:
            fuel_cell_in, fuel_cell_out, fuel_cell_ctrl = fuel_cell(net_power, net_gas, net_hyd, multinet)
    
        
        # ppipes.pipeflow(net_gas)
        # print(net_gas.res_junction)
        run_control(multinet)
        # print('P2G 1:', net_gas.res_source)
        
        if net_power.gen['p_mw'][0] > net_power.load['p_mw'][0]:
            print('Electrolyser out: ',net_hyd.source.loc[electzr_out, 'mdot_kg_per_s'])
            if i == 0:
                LoG[i] = LoG[0] + net_hyd.source.loc[electzr_out, 'mdot_kg_per_s'] / Storage_Cap 
            else:
                LoG[i] = LoG[i-1] + net_hyd.source.loc[electzr_out, 'mdot_kg_per_s'] / Storage_Cap 
                
        if net_power.gen['p_mw'][0] < net_power.load['p_mw'][0]:
            print('Fuel cell in: ',net_hyd.sink.loc[fuel_cell_in, 'mdot_kg_per_s'])
            if i == 0:
                LoG[i] = LoG[0] - net_hyd.sink.loc[fuel_cell_in, 'mdot_kg_per_s'] / Storage_Cap 
            else:
                LoG[i] = LoG[i-1] - net_hyd.sink.loc[fuel_cell_in, 'mdot_kg_per_s'] / Storage_Cap 
        
    
        
        print(' -------------Result ext grid-------------')
        print(net_hyd.res_ext_grid)
    plot(LoG)
       
  

    
main()

**Comment by akhiljoseph007** [comment] 2022-08-17 13:37
[Sample code.txt](https://github.com/e2nIEE/pandapipes/files/9363113/Sample.code.txt)
Hi jkisse,

Thanks for the quick response. Please find the attached code. 

I draw your kind attention to line 120. This line add the P2G to the network. If you comment this one the code will work.

**Comment by jkisse** [comment] 2022-08-17 15:17
Thanks. I only had the time for a first short look on the code. Please try to assign different levels to the controllers by adding the kwarg level=...
The example worked for me when I set the level to 1 for one controller and the other one remains on 0 (default).
I'll have a deeper look when I have more time.
P.S. I've noticed that there is no pipe in the h2 network - this might lead to unexpected behaviour.

**Comment by akhiljoseph007** [comment] 2022-08-17 15:37
Hi Jkisse,

Thanks for the reply. I will try by adding the kwarg level. Please note my objective elaborated below when you have a deeper look at the code. Thanks.

Answer to **P.S. I've noticed that there is no pipe in the h2 network - this might lead to unexpected behaviour**.

There's is no pipe in the H2 network because I am trying to time series model a combo of Electrolyser- StorageTank-Fuel cell based vector coupling storage device. There are two hydrogen junctions to couple electrolyser (e_bus to hydrogen junction 0) and fuel-cell (hydrogen junction 1 to e_bus). Electrolyser is modelled using P2G and fuel cell using G2P.
Junctions are open and I have to do something so that by end of the simulation I can trigger the electrolyser when power is surplus and fuel cell when power is deficit. And I should have the change in Level-of-Gas (like change in SoC in battery).

As far as I believe there is no direct way to model this in pandapipes. That why i had to go like this, Please advice me if you have any other approach in mind. Thanks a lot.

**Comment by jkisse** [comment] 2022-08-30 09:09
Thanks again for reporting the error. @SimonRubenDrauz fixed this in PR #402, so the error should be resolved, even if all controllers have the same level. You can install it from the develop branch by cloning the repository or simply by using pip: 
`pip install git+https://github.com/e2nIEE/pandapipes.git@develop`

**Comment by dlohmeier** [comment] 2023-05-23 05:38
Since this issue seems to be solved, I will close it for now, but feel free to re-open in case of problems.

**Closed by dlohmeier** 2023-05-23 05:38 UTC
