### ISSUE TITLE
heat calculation problem: resulting temperature values < 273 K

### ISSUE THREAD

**Issue by piotre13** [e2nIEE/pandapipes#417] opened 2022-10-20 13:16 UTC
Hello,
I'm using pandapipes to model a district heating network. I'm modelling it as a closed circuit. It is composed of a radial network of nodes (202) and pipes (201) for the delivery and its mirrored (reversed) version for the return. These two are connected with heatexchangers at the leafs and a circulation pump (constant) mass between the two root nodes.
I'm performing the pipeflow calculation in mode='all' because I'm interested in the resulting temperatures across the nodes.
the boundary conditions I'm imposing are :
- the mass flow and the temperature of the circulation pump
- the heat extracted at the heatexchangers

The pipeflow run and both the hydraulics and thermal problem converge, but the problem is that the heat calculation returns unacceptable temperature values (< 273 K) for the return portion of the network.
the network is taken by a real world topology (connections, lengths, diameters and so on are real), the mass flow values are real, the extracted power is real and expressed in W.
How is it possible? may you have some suggestion? possible things to check? In the heat calculation shouldn't be present a check on the temperature values to ensure their physical feasibility?

Thanks in advance to any possible suggestions

**Comment by jkisse** [comment] 2022-10-20 13:47
Hi [piotre13](https://github.com/piotre13), thanks for using pandapipes and reaching out to us. A few ideas come to my mind to investigate the problem:

1. How does the temperature evolve along the junctions, does < 273 K early or only for a few junctions at the end?
2. Please confirm that the pipe parameters "heat loss" (`qext_w`, `alpha_w_per_m2k`) and "ambient temperature" (`text_k`) are fine. If the heat loss is > 0, try to set it to 0 for debugging the problem.
4. Please make sure that you have a reasonable roughness, e.g. `k=0.05` (1 mm is usually way too rough). For debugging, you can also set it to an even lower value to check if the hydraulics might cause the problem.
3. Do you see an improvement if you increase the `sections` per pipe (internal resoltion)?

**Comment by piotre13** [comment] 2022-10-20 14:21
Thanks a lot for the fast response!
1. the nodes that reaches temperature <273 K are all in the return portion some of them are just downstream some heatexchangers (26 out of 69).
2. qext_w =0.0 (as default), alpha = 10 and t_ext = 283
3. i've tested new roughness of 0.05 but the problem persist, actually the hydraulics seem to work fine. The output velocities are rather small (maybe this is a problem)
4. augmenting sections seem to improve it a little bit, the number o nodes with T<273 remains the same but the magnitude of the deviation from 273 is smaller
Another thing is that for debugging purposes i'm extracting really small power values from the heatexchangers (P=4000W) Thus i'm not capable of explaining why is just at the end of some heatexchangers that mistakes are firstly generated.

**Comment by jkisse** [comment] 2022-10-20 15:58
Could you please provide a minimal example that reproduces the problem?

**Comment by dlohmeier** [comment] 2022-10-20 20:18
I would like to raise another question on this problem. In general of course, I agree with @jkisse that it is most helpful to look at an examplary problem formulation with the underlying grid topology to understand what is going on there, so if you could provide something like that, I am pretty sure that we will find out what happens and were the error appears. I assume that you have parallel branches on which you extract the heat between flow and return. Does the hydraulic result look reasonable there? We are about to release a new component called flow_control that can help to direct the flows in a heating grid, otherwise the mass flows entering each of the parallel branches and going through the heat exchangers are just bound by the physical resistances (i.e. pipe friction and pressure losses due to bendings etc.), which should be very hard to model. In such cases, the mass flow might split up on the parallel branches in such a way that some heat exchangers experience a large mass flow while others are very small. Yet, the extracted heat is independent of mass flow and temperature drops, it could even lead to results below 0 K at the exit point of the heat exchanger, if I'm not mistaken. Checking the physical feasibility would be reasonable to do, however we could only output a warning and not offer a solution within the pipeflow calculation. Can you check if the small temperatures appear only within the parallel branches (and maybe some parts of the return where those branches are brought together, but at the end of the network)? If this is the case and in the united return stream the temperature looks reasonable, I strongly recommend having a look at the flow controllers or finding another way to suitably distribute the mass flows along the parallel branches.

**Comment by dlohmeier** [comment] 2023-02-13 12:23
Hello @piotre13 ,
were you able to solve the problem? If so, I would like to close the issue, otherwise maybe we can continue the discussion and try to still fix the problem you encountered?

**Comment by dlohmeier** [comment] 2023-05-23 05:36
I will close the issue for now, please feel free to re-open if the problem still exists or any further problems arise.

**Closed by dlohmeier** 2023-05-23 05:36 UTC
Labels: heating
